# Generated by Django 4.0.4 on 2022-04-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('titlepic', models.ImageField(upload_to='')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Date added')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Firstname*')),
                ('lastname', models.CharField(max_length=100, verbose_name='Lastname*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*')),
                ('tel', models.CharField(blank=True, max_length=26, null=True, verbose_name='Phonenumber*')),
                ('message', models.TextField(verbose_name='Message')),
                ('inquiry_send_at_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('checked', models.BooleanField(default=False, verbose_name='Solved?')),
            ],
        ),
    ]
